export const RESOURCE_LOADING = 'RESOURCE_LOADING';
export const RESOURCE_SUCCESS = 'RESOURCE_SUCCESS';
export const RESOURCE_FAIL = 'RESOURCE_FAIL';
export const SAVE_RESOURCE_DETAILS_LOADING = 'SAVE_RESOURCE_DETAILS_LOADING';
export const SAVE_RESOURCE_DETAILS_SUCCESS = 'SAVE_RESOURCE_DETAILS_SUCCESS';
export const SAVE_RESOURCE_DETAILS_FAIL = 'SAVE_RESOURCE_DETAILS_FAIL';
