export const ADD_RESOURCE_LOADING = 'ADD_RESOURCE_LOADING';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAIL = 'ADD_RESOURCE_FAIL';
export const GET_RESOURCE_FIELDS_SUCCESS = 'GET_RESOURCE_FIELDS_SUCCESS';
export const GET_RESOURCE_FIELDS_FAIL = 'GET_RESOURCE_FIELDS_FAIL';
export const GET_RESOURCE_FIELDS_LOADING = 'GET_RESOURCE_FIELDS_LOADING';
